[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true        #alows foundary to directly run commands on your machine(new command that are not in foundary books)
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
